/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-26 17:13:51 UTC)
 * on 2013-09-10 at 16:14:34 UTC 
 * Modify at your own risk.
 */

package com.doubleencore.android.pushdontpoll.dateendpoint;

/**
 * Service definition for Dateendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link DateendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Dateendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the dateendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://flowing-elf-321.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "dateendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Dateendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Dateendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "currentDate".
   *
   * This request holds the parameters needed by the the dateendpoint server.  After setting any
   * optional parameters, call the {@link CurrentDate#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public CurrentDate currentDate() throws java.io.IOException {
    CurrentDate result = new CurrentDate();
    initialize(result);
    return result;
  }

  public class CurrentDate extends DateendpointRequest<com.doubleencore.android.pushdontpoll.dateendpoint.model.CurrentDate> {

    private static final String REST_PATH = "currentdate";

    /**
     * Create a request for the method "currentDate".
     *
     * This request holds the parameters needed by the the dateendpoint server.  After setting any
     * optional parameters, call the {@link CurrentDate#execute()} method to invoke the remote
     * operation. <p> {@link
     * CurrentDate#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected CurrentDate() {
      super(Dateendpoint.this, "GET", REST_PATH, null, com.doubleencore.android.pushdontpoll.dateendpoint.model.CurrentDate.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public CurrentDate setAlt(java.lang.String alt) {
      return (CurrentDate) super.setAlt(alt);
    }

    @Override
    public CurrentDate setFields(java.lang.String fields) {
      return (CurrentDate) super.setFields(fields);
    }

    @Override
    public CurrentDate setKey(java.lang.String key) {
      return (CurrentDate) super.setKey(key);
    }

    @Override
    public CurrentDate setOauthToken(java.lang.String oauthToken) {
      return (CurrentDate) super.setOauthToken(oauthToken);
    }

    @Override
    public CurrentDate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CurrentDate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CurrentDate setQuotaUser(java.lang.String quotaUser) {
      return (CurrentDate) super.setQuotaUser(quotaUser);
    }

    @Override
    public CurrentDate setUserIp(java.lang.String userIp) {
      return (CurrentDate) super.setUserIp(userIp);
    }

    @Override
    public CurrentDate set(String parameterName, Object value) {
      return (CurrentDate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "sendTickle".
   *
   * This request holds the parameters needed by the the dateendpoint server.  After setting any
   * optional parameters, call the {@link SendTickle#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public SendTickle sendTickle() throws java.io.IOException {
    SendTickle result = new SendTickle();
    initialize(result);
    return result;
  }

  public class SendTickle extends DateendpointRequest<Void> {

    private static final String REST_PATH = "sendTickle";

    /**
     * Create a request for the method "sendTickle".
     *
     * This request holds the parameters needed by the the dateendpoint server.  After setting any
     * optional parameters, call the {@link SendTickle#execute()} method to invoke the remote
     * operation. <p> {@link
     * SendTickle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected SendTickle() {
      super(Dateendpoint.this, "POST", REST_PATH, null, Void.class);
    }

    @Override
    public SendTickle setAlt(java.lang.String alt) {
      return (SendTickle) super.setAlt(alt);
    }

    @Override
    public SendTickle setFields(java.lang.String fields) {
      return (SendTickle) super.setFields(fields);
    }

    @Override
    public SendTickle setKey(java.lang.String key) {
      return (SendTickle) super.setKey(key);
    }

    @Override
    public SendTickle setOauthToken(java.lang.String oauthToken) {
      return (SendTickle) super.setOauthToken(oauthToken);
    }

    @Override
    public SendTickle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SendTickle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SendTickle setQuotaUser(java.lang.String quotaUser) {
      return (SendTickle) super.setQuotaUser(quotaUser);
    }

    @Override
    public SendTickle setUserIp(java.lang.String userIp) {
      return (SendTickle) super.setUserIp(userIp);
    }

    @Override
    public SendTickle set(String parameterName, Object value) {
      return (SendTickle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "sendUpdate".
   *
   * This request holds the parameters needed by the the dateendpoint server.  After setting any
   * optional parameters, call the {@link SendUpdate#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public SendUpdate sendUpdate() throws java.io.IOException {
    SendUpdate result = new SendUpdate();
    initialize(result);
    return result;
  }

  public class SendUpdate extends DateendpointRequest<Void> {

    private static final String REST_PATH = "sendUpdate";

    /**
     * Create a request for the method "sendUpdate".
     *
     * This request holds the parameters needed by the the dateendpoint server.  After setting any
     * optional parameters, call the {@link SendUpdate#execute()} method to invoke the remote
     * operation. <p> {@link
     * SendUpdate#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected SendUpdate() {
      super(Dateendpoint.this, "POST", REST_PATH, null, Void.class);
    }

    @Override
    public SendUpdate setAlt(java.lang.String alt) {
      return (SendUpdate) super.setAlt(alt);
    }

    @Override
    public SendUpdate setFields(java.lang.String fields) {
      return (SendUpdate) super.setFields(fields);
    }

    @Override
    public SendUpdate setKey(java.lang.String key) {
      return (SendUpdate) super.setKey(key);
    }

    @Override
    public SendUpdate setOauthToken(java.lang.String oauthToken) {
      return (SendUpdate) super.setOauthToken(oauthToken);
    }

    @Override
    public SendUpdate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SendUpdate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SendUpdate setQuotaUser(java.lang.String quotaUser) {
      return (SendUpdate) super.setQuotaUser(quotaUser);
    }

    @Override
    public SendUpdate setUserIp(java.lang.String userIp) {
      return (SendUpdate) super.setUserIp(userIp);
    }

    @Override
    public SendUpdate set(String parameterName, Object value) {
      return (SendUpdate) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Dateendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Dateendpoint}. */
    @Override
    public Dateendpoint build() {
      return new Dateendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link DateendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setDateendpointRequestInitializer(
        DateendpointRequestInitializer dateendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(dateendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
